spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: integral-erp

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}

  server:
    port: ${PORT:8080}

  cors:
    frontend-url: ${FRONTEND_URL}

  usuarioadmin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

  mercadopago:
    access-token: ${MP_ACCESS_TOKEN}

  melhorenvio:
    token: ${MELHOR_ENVIO_TOKEN}

  supabase:
    supabase-url: ${SUPABASE_URL}
    anon-key: ${ANON_KEY}
    bucket: produtos
